### ISSUE TITLE
Molecule Failed to validate: artifactory-ubuntu-latest is not unique

### ISSUE THREAD

**Issue by M0nn0M** [robertdebock/ansible-role-artifactory#1]
Hello,

I hope this is not a newbie issue but my Molecule test failed.

**Steps followed**
I installed artifactory ansible role, everything worked great.
Then I launched the command: 'molecule test'

**Error message**
I have the following error message: 
ERROR: Failed to validate.

{'platforms': [{0: [{'name': ["'artifactory-ubuntu-latest' is not unique"]}], 1: [{'name': ["'artifactory-ubuntu-latest' is not unique"]}], 2: [{'name': ["'artifactory-ubuntu-latest' is not unique"]}], 3: [{'name': ["'artifactory-ubuntu-latest' is not unique"]}], 4: [{'name': ["'artifactory-ubuntu-latest' is not unique"]}], 5: [{'name': ["'artifactory-ubuntu-latest' is not unique"]}], 6: [{'name': ["'artifactory-ubuntu-latest' is not unique"]}], 7: [{'name': ["'artifactory-ubuntu-latest' is not unique"]}], 8: [{'name': ["'artifactory-ubuntu-latest' is not unique"]}], 9: [{'name': ["'artifactory-ubuntu-latest' is not unique"]}], 10: [{'name': ["'artifactory-ubuntu-latest' is not unique"]}], 11: [{'name': ["'artifactory-ubuntu-latest' is not unique"]}], 12: [{'name': ["'artifactory-ubuntu-latest' is not unique"]}], 13: [{'name': ["'artifactory-ubuntu-latest' is not unique"]}], 14: [{'name': ["'artifactory-ubuntu-latest' is not unique"]}]}]}

**Environment**
- Control node OS: Ubuntu 16.0.4
- Control node Ansible version: 2.7.9

Thank you for your help

**Comment by robertdebock** [comment]
I'll have a look, I guess I've made a mistake somewhere.

**Comment by robertdebock** [comment]
This was a problem, well spotted. It was solved in the `master` branch, but not released.

I've just released version 2.0.1 that addresses this issue. Give Travis some 40 minutes to test and release to Galaxy and this issue should be gone.

**Comment by M0nn0M** [comment]
Thanks for this fast reply! I'll will reinstall the role then 👍

**Comment by M0nn0M** [comment]
Hi, I just retested the role.

Is there something I am doing wrong?

Here is the error message:

ERROR: 
An error occurred during the test sequence action: 'destroy'. Cleaning up.
--> Scenario: 'default'
--> Action: 'destroy'
    
    PLAY [Destroy] *****************************************************************
    
    TASK [Destroy molecule instance(s)] ********************************************
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost]
    
    TASK [Wait for instance(s) deletion to complete] *******************************
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=1    changed=1    unreachable=0    failed=1

**Comment by robertdebock** [comment]
I'm guessing you miss a few packages, you can troubleshoot molecule by adding the `--debug` flag.

You can also try an [ansible development environments](https://github.com/robertdebock/ansible-development-environment) in Vagrant.

Hope that helps.

**Comment by M0nn0M** [comment]
Thanks for the link.
I run a Ubuntu 16.04 but it seems that the setup (ansible development environments) is using yum at some point and failing instead of skipping this part (?). I installed yum anyway but still, I have this error (below). Which repo is needed please?
Thanks


TASK [robertdebock.bootstrap : install software with pkg_add] **********************************************************************
Tuesday 16 April 2019  16:25:57 +0200 (0:00:00.034)       0:00:04.683 ********* 
skipping: [localhost]

TASK [robertdebock.bootstrap : install software with yum] **************************************************************************
Tuesday 16 April 2019  16:25:57 +0200 (0:00:00.029)       0:00:04.712 ********* 
FAILED - RETRYING: install software with yum (3 retries left).
FAILED - RETRYING: install software with yum (2 retries left).
FAILED - RETRYING: install software with yum (1 retries left).
fatal: [localhost]: FAILED! => changed=true 
  attempts: 3
  msg: non-zero return code
  rc: 1
  stderr: |-
    There are no enabled repos.
     Run "yum repolist all" to see the repos you have.
     You can enable repos with yum-config-manager --enable <repo>
  stderr_lines:
  - There are no enabled repos.
  - ' Run "yum repolist all" to see the repos you have.'
  - ' You can enable repos with yum-config-manager --enable <repo>'
  stdout: ''
  stdout_lines: <omitted>

PLAY RECAP *************************************************************************************************************************
localhost                  : ok=11   changed=0    unreachable=0    failed=1   

Tuesday 16 April 2019  16:26:13 +0200 (0:00:15.590)       0:00:20.303 ********* 
=============================================================================== 
robertdebock.bootstrap ------------------------------------------------- 20.23s
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
total ------------------------------------------------------------------ 20.23s

**Comment by M0nn0M** [comment]
> >  Thanks for the link.
> >  I run a Ubuntu 16.04 but it seems that the setup (ansible development environments) is using yum at some point and failing instead of skipping this part (?). I installed yum anyway but still, I have this error (below). Which repo is needed please?
> >  Thanks
> >  
> >  TASK [robertdebock.bootstrap : install software with pkg_add] **********************************************************************
> >  Tuesday 16 April 2019 16:25:57 +0200 (0:00:00.034) 0:00:04.683 *********
> > skipping: [localhost]
> >  
> >  TASK [robertdebock.bootstrap : install software with yum] **************************************************************************
> >  Tuesday 16 April 2019 16:25:57 +0200 (0:00:00.029) 0:00:04.712 *********
> >  FAILED - RETRYING: install software with yum (3 retries left).
> >  FAILED - RETRYING: install software with yum (2 retries left).
> >  FAILED - RETRYING: install software with yum (1 retries left).
> >  fatal: [localhost]: FAILED! => changed=true
> >  attempts: 3
> >  msg: non-zero return code
> >  rc: 1
> >  stderr: |-
> >  There are no enabled repos.
> >  Run "yum repolist all" to see the repos you have.
> >  You can enable repos with yum-config-manager --enable
> >       stderr_lines:
> >      
> >      There are no enabled repos.
> > 
> >      ' Run "yum repolist all" to see the repos you have.'
> > 
> >      ' You can enable repos with yum-config-manager --enable '
> >      stdout: ''
> >       stdout_lines:
> > 
> > 
> >  PLAY RECAP *************************************************************************************************************************
> >  localhost : ok=11 changed=0 unreachable=0 failed=1
> > 
> >  Tuesday 16 April 2019 16:26:13 +0200 (0:00:15.590) 0:00:20.303 *********
> > 
> >  robertdebock.bootstrap ------------------------------------------------- 20.23s
> > 
> > ``
> >  total ------------------------------------------------------------------ 20.23s
> > ```
> 

I commented the yum part (in ansible-development-environment/roles/robertdebock.boostrap/tasks/main.yml from line 160 to 169) and it went through, please tell me if the part is required or not.**

Thanks

**Comment by M0nn0M** [comment]
Nope still having errors when launching molecule test:

      160:1     warning  comment not indented like content  (comments-indentation)
    
An error occurred during the test sequence action: 'lint'. Cleaning up.
--> Scenario: 'default'
--> Action: 'destroy'
    
    PLAY [Destroy] *****************************************************************
    
    TASK [Destroy molecule instance(s)] ********************************************
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost] => (item=None)
    changed: [localhost]
    
    TASK [Wait for instance(s) deletion to complete] *******************************
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    failed: [localhost] (item=None) => {"attempts": 1, "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    fatal: [localhost]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=1    changed=1    unreachable=0    failed=1   
    
    
ERROR:

**Comment by robertdebock** [comment]
I think you're seeing two issues:

```
TASK [robertdebock.bootstrap : install software with yum] **************************************************************************
Tuesday 16 April 2019 16:25:57 +0200 (0:00:00.029) 0:00:04.712 *********
FAILED - RETRYING: install software with yum (3 retries left).
FAILED - RETRYING: install software with yum (2 retries left).
FAILED - RETRYING: install software with yum (1 retries left).
fatal: [localhost]: FAILED! => changed=true
attempts: 3
msg: non-zero return code
rc: 1
stderr: |-
There are no enabled repos.
Run "yum repolist all" to see the repos you have.
You can enable repos with yum-config-manager --enable
```

The task above tries to install `python` and `sudo`. It appears your machine does not have access to install these packages.

The other issue:
```
  160:1     warning  comment not indented like content  (comments-indentation)
```

Is about incorrect comments.

In yaml when you comment, the spaces should be correct. See [this documentation](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments_indentation).

Hope this helps you.

**Comment by M0nn0M** [comment]
Yes, it helps. Thanks.
Access to what please?  
Your repo? Or a package manager? 
I think I need a URL to configure my machine

**Comment by robertdebock** [comment]
Access to repositories to install packages from. I think if you manually connect to the machine and run a test like `yum install screen`, you will also see an issue.

**Comment by M0nn0M** [comment]
Hey Robert,
Do you organize workshops, meetups, trainings or tutorings? 🙏
