### ISSUE TITLE
Configuring through ansible?

### ISSUE THREAD

**Issue by micabytes** [robertdebock/ansible-role-artifactory#2]
Is there anyway to configure the server without going through the welcome screen and configuring repositories through the GUI? Ideally, I'd prefer all of that to be configured as part of the code, so that I don't need to try and replicate that in different environments/clouds.

Artifactory seems to have the APIs to do this, from what I can see, so wondering if you use that.

**Comment by robertdebock** [comment]
Good idea, I'll dive into it and see what I can come up with.

**Comment by robertdebock** [comment]
I would need some help with this, keeping the issue open for anybody to help out.

**Comment by micabytes** [comment]
In hindsight, I think this may not actually be worth doing. The main problem is that if you need to do anything serious, you'd probably have to assume a Pro license, since most of the good API's are locked away there.

My basic assumption right now is that the easiest way to handle this is to do an install, log in as admin/password and do the basic setup you want once, then take a backup of the base system setup and do a restore/import every time you need to redeploy from scratch. Unless you need a multi-site setup (in which case you probably have the resources to custom-build anyway), that is probably sufficient for most simple use cases.

**Comment by micabytes** [comment]
Incidentally, the "set password for artifactory for version 6.8.0 and above" does not work for me.

Currently, you are trying to set the password before the service has started, which fails unless artifactory is already running.

But even if I shift this to after the service has started, I get an error (invalid credentials) when trying to set the admin user. Very weird.

**Comment by weakcamel** [comment]
Posting in case someone were to attempt that: https://www.jfrog.com/confluence/display/RTF/Getting+Started#GettingStarted-ArtifactoryBootstrapYAMLFile

Agreed with @micabytes comment:

> In hindsight, I think this may not actually be worth doing. 

 Artifactory's deployment is a bit awkward when using Ansible; the mutable state is is stored in multiple config files + datastore + database; backup/restore is what worked for me reasonably well so far.

**Comment by robertdebock** [comment]
I'll close this issue as it seems a bit daunting right now.

Thanks @micabytes and @weakcamel for helping!
