### ISSUE TITLE
allowing installation of different flavours of Artifactory

### ISSUE THREAD

**Issue by weakcamel** [robertdebock/ansible-role-artifactory#5]
**Is your feature request related to a problem? Please describe.**

Current code assumes installation of OSS flavour of Artifactory, although there are other ones out there in the wild: `cpp-ce`, `jcr` and also `pro`.

One can override role variables (`artifactory_zip`, `artifactory_home`) to use a different URL and create a different `ARTIFACTORY_HOME`, yet the following line:

https://github.com/robertdebock/ansible-role-artifactory/blob/105bc568a856c766e9e3b690d2671c7dcba44755/tasks/main.yml#L49

still assumes the path will contain `artifactory-oss`.

**Describe the solution you'd like**

I believe the changes necessary to support a "pro" or any other flavour of Artifactory installation would include:

- using `artifactory_home` within the [tasks/main](https://github.com/robertdebock/ansible-role-artifactory/blob/master/tasks/main.yml) instead of the hardcoded string
- add an `artifactory_flavour` (or similar) variable in defaults/main.yml with default value of `oss` (for backward compatibility) yet allowing to override that
- use the new variable to derive the download URL and ARTIFACTORY_HOME
- as the "Pro" is hosted at slightly different URL which doesn't follow the free versions' pattern, perhaps just add a note mentioning that it would need to be overridden?

**Describe alternatives you've considered**

Writing my own Ansible role - which I'd rather not do :)

**Additional context**

Download URL for the "pro" versions is https://jfrog.bintray.com/artifactory-pro/org/artifactory/pro/jfrog-artifactory-pro/6.16.0/ (a special snowflake, compared to the other versions which are available at https://dl.bintray.com/jfrog/artifactory/

**Comment by weakcamel** [comment]
BTW, if the issue makes sense, I should be able to provide a PR with the change needed.

**Comment by robertdebock** [comment]
Well, I'm really open to a PR. Feel free to fork, modify and show your plan.

**Comment by bbaassssiiee** [comment]
This is only possible until Artifactory 6, latest release 02-Dec-2019.
